name: URL Shortener

title: Anchr.cf URL Shortener
description: URL Shortener for Jalish Mahmud Sujon ✂️🔗

version: v0.2

baseurl: ""
permalink: /:slug/
logo: /assets/logo.png
google_analytics: G-FGC93CVVBW
theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: true
    permalink: /:slug/

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
